{% set name = "quantiphy" %}
{% set version = "2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba5375ac55c3b90077a793588dd5a88aaf81b2c3b0fc9c9359513ac39f6ed84d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=2
  run:
    - python >={{ python_min }}

test:
  imports:
    - quantiphy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://quantiphy.readthedocs.io/
  summary: 'QuantiPhy is a Python library that offers support for physical quantities'
  description: |
    Author - Ken Kundert
    QuantiPhy is a Python library that offers support for physical quantities.
    A quantity is the pairing of a number and a unit of measure that indicates
    the amount of some measurable thing. QuantiPhy provides quantity objects
    that keep the units with the number, making it easy to share them as single
    object. They subclass float and so can be used anywhere a real number is
    appropriate.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://quantiphy.readthedocs.io/
  dev_url: https://github.com/kenkundert/quantiphy

extra:
  recipe-maintainers:
    - danielbrown2
    - KenKundert
